recipes/urls.py
from django.conf.urls import include, url
from recipes import views

urlpatterns = [
    #list views
    url(r'^$', views.recipes, name='recipes'),
    url(r'^categories/(?P<category_id>\d+)/$', views.category, name='category'),

    # detail views
    url(r'^(?P<recipe_id>\d+)/$', views.recipe, name='recipe'),
    url(r'^cook/(?P<recipe_id>\d+)/$', views.recipe, name='cook'),
    url(r'^ingredients/(?P<ingredient_id>\d+)/$', views.ingredient, name='ingredient'),

    # recipe CRUD
    url(r'^create/$', views.create_recipe, name='create'),
    url(r'^update/(?P<recipe_id>\d+)/$', views.update_recipe, name='update'),
    url(r'^delete/(?P<recipe_id>\d+)/$', views.delete_recipe, name='delete'),

    # perform recipe
    url(r'^perform/(?P<recipe_id>\d+)/$', views.perform_recipe_serves, name='perform_serves'),
    url(r'^perform/(?P<recipe_id>\d+)/(?P<serves>\d+)/$', views.perform_recipe, name='perform'),

    # plan
    # url(r'^meal_plan/$', views.meal_plan, name='meal_plan'),
    url(r'^update_meal_plan/$', views.update_meal_plan, name='update_meal_plan'),
]

recipes/models.py
import datetime

from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.urlresolvers import reverse
from django.db import models#, transaction
from django.utils.html import format_html

from accounts.models import UserProfile
from recipes.utils.queries import RecipesQueries
# from products.models import Product

# MANAGERS

class LeftOversManager(models.Manager):
    def oldest_leftovers(self, user_profile):
        return self.filter(user_profile=user_profile, is_consumed=False).order_by('pub_date')

class RecipeManager(models.Manager):
    def latest_recipes(self):
        return self.order_by('-pub_date')[:5]
        
    def recipes_in_category(self, category):
        return category.recipe_set.all()

    def recommended_recipes(self, user_profile):
        queries_util = RecipesQueries(user_profile)
        return queries_util.get_doable_recipes_queryset(self.all())

    def recommended_recipes_dict(self, user_profile):
        queries_util = RecipesQueries(user_profile)
        return queries_util.get_doable_recipes_dict(self.all())

class MealDayManager(models.Manager):
    def get_or_create_meal_day(self, user_profile, day):
        # deal with 'get' exceptions
        try:
            meal_day = self.get(user_profile=user_profile, day=day)
            return meal_day
        except self.model.DoesNotExist:
            meal_day = MealDay(user_profile=user_profile, day=day)
            meal_day.save()
            return meal_day

# MODELS

class IngredientCategory(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "ingreident categories"

    # methods
    def __str__(self):
        return self.name

class Ingredient(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(IngredientCategory)
    image = models.ImageField(upload_to="ingredients/", blank=True, null=True)

    assertable = models.NullBooleanField(blank=True)

    # gluten = models.NullBooleanField(blank=True)
    
    # if ingredient is normally measured in special units, e.g. eggs, get the factor to grams from here
    factor_to_grams = models.FloatField(blank=True, null=True, validators = [MinValueValidator(0), MaxValueValidator(1000000)])

    # nutrition facts
    serving_size = models.IntegerField(default=100)

    # calories
    calories = models.IntegerField(default=0)
    calories_from_fat  = models.IntegerField(default=0)
    
    # fats
    total_fat = models.IntegerField(default=0)
    saturated_fat = models.IntegerField(default=0)
    trans_fat = models.IntegerField(default=0)
    mono_fat = models.IntegerField(default=0)
    polin_fat = models.IntegerField(default=0)
    

    # cholesterol in mg
    cholesterol = models.IntegerField(default=0)

    # mineral salts in mg
    sodium = models.IntegerField(default=0)
    calcium = models.IntegerField(default=0)
    potassium = models.IntegerField(default=0)
    iron = models.IntegerField(default=0)

    # carbs
    total_carbs = models.IntegerField(default=0)
    dietary_fiber = models.IntegerField(default=0)
    sugars = models.IntegerField(default=0)
    added_sugars = models.IntegerField(default=0)

    # protein
    protein = models.IntegerField(default=0)

    # vitamines in mg
    vitamin_a = models.IntegerField(default=0)
    vitamin_b6 = models.IntegerField(default=0)
    vitamin_b12 = models.IntegerField(default=0)
    vitamin_c = models.IntegerField(default=0)
    vitamin_d = models.IntegerField(default=0)
    vitamin_e = models.IntegerField(default=0)
    
    # methods
    def __str__(self):
        return self.name

class RecipeCategory(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = "recipe category"
        verbose_name_plural = "recipe categories"
    
    # methods
    def __str__(self):
        return self.name    
    
class Recipe(models.Model):
    name = models.CharField(max_length=50)
    author = models.ForeignKey(UserProfile)
    pub_date = models.DateTimeField('date published', auto_now=True)
    preparation_time = models.PositiveIntegerField()
    cooking_time = models.PositiveIntegerField()
    ready_in_time = models.PositiveIntegerField()
    serves = models.PositiveIntegerField()
    categories = models.ManyToManyField(RecipeCategory)
    # dificulty ?
    # ingredients = models.ManyToManyField(RecipeIngredient)
    # instructions = models.TextField()
    
    # manager
    objects = RecipeManager()

    # methods
    def __str__(self):
        return self.name

    def clean(self):
        if self.ready_in_time < self.cooking_time + self.preparation_time:
            raise ValidationError({'preparation_time':["Must be greater than the sum of cooking and preparation time!"]})

class RecipeFinalImage(models.Model):
    recipe = models.ForeignKey(Recipe)
    image = models.ImageField(upload_to="recipes/", blank=True, null=True)

class Unit(models.Model):
    name = models.CharField(max_length=50)
    # at this time we assume that all cooking liquids have a density ~= to water
    # factor such that quantity_in_other_unit * other_unit.factor_to_grams = quantity_in_grams
    # exception if factor_to_grams == 0
    # factor_to_grams = models.PositiveIntegerField()
    factor_to_grams = models.FloatField(validators = [MinValueValidator(0), MaxValueValidator(1000000)])

    # methods
    def __str__(self):
        return self.name
        
    # def convert(self, quantity, unit_to_convert):
    #     return quantity * self.factor_to_grams

class RecipeIngredient(models.Model):
    quantity = models.PositiveIntegerField()
    unit = models.ForeignKey(Unit)
    ingredient = models.ForeignKey(Ingredient)
    recipe = models.ForeignKey(Recipe)

    # methods
    def get_factor_to_grams(self):
        if self.unit.factor_to_grams != 0:
            return self.unit.factor_to_grams
        else:
            if self.ingredient.factor_to_grams:
                return self.ingredient.factor_to_grams
            else:
                # TODO: escape this case in form validation
                return 0

    def get_quantity_in_grams(self):
        return self.quantity * self.get_factor_to_grams()

    def __str__(self):
        return str(self.quantity) + " " + str(self.unit) + " de " + str(self.ingredient.name)

    def html_str(self):
        return format_html(str(self.quantity) + " " + str(self.unit) + " de <a href=\"" + reverse('recipes:ingredient', args=(self.ingredient.id,)) + "\">" + str(self.ingredient) + "</a>")


class RecipeStep(models.Model):
    text = models.TextField()
    image = models.ImageField(upload_to="recipes/", blank=True, null=True)
    recipe = models.ForeignKey(Recipe)
    
    # TODO: change for better ordering system!
    class Meta:
        ordering=('id',)

class CookedRecipe(models.Model):
    recipe = models.ForeignKey(Recipe)
    user_profile = models.ForeignKey(UserProfile)
    date_cooked = models.DateTimeField('date cooked', auto_now=True)
    serves_cooked = models.IntegerField()
    serves_consumed = models.IntegerField(default=0)
    is_consumed = models.BooleanField(default=False)
    
    # manager
    objects = LeftOversManager()

    # methods
    def consume(self, serves):
        total_consumed = self.serves_consumed + serves
        if total_consumed < self.serves_cooked:
            self.serves_consumed = total_consumed
        else:
            # ASSUME total_consumed == self.serves_cooked
            # TODO: see how to deal with total_consumed > self.serves_cooked
            self.serves_consumed = self.serves_cooked
            self.is_finished = True

class Meal(models.Model):
    # user_profile = models.ForeignKey(UserProfile)
    # day = models.DateField()

    # CONTSANTS
    LUNCH = 0
    DINNER = 1
    MEAL_TYPE_CHOICES = ((LUNCH, 'Lunch'), (DINNER, 'Dinner'))

    meal_type = models.CharField(max_length=1, choices=MEAL_TYPE_CHOICES)
    
    first_course = models.ForeignKey(CookedRecipe, related_name="firstcourse")
    first_course_serves = models.IntegerField()

    second_course = models.ForeignKey(CookedRecipe, related_name="secondcourse")
    second_course_serves = models.IntegerField()

class MealDay(models.Model):
    user_profile = models.ForeignKey(UserProfile)
    day = models.DateField()
    
    lunch = models.OneToOneField(Meal, related_name="lunch", blank=True, null=True)
    dinner = models.OneToOneField(Meal, related_name="dinner", blank=True, null=True)

    # manager
    objects = MealDayManager()

recipes/templates/recipes/create_recipe.html
{% extends "base.html" %}

{% block title %}Nueva Receta - {{ block.super }}{% endblock %}

{% block main_content %}

<h2>Nueva Receta</h2>

{% include "recipes/recipe_form.html" %}

{% endblock %}

recipes/templates/recipes/delete_recipe.html
{% extends "base.html" %}

{% block title %}Eliminar Receta - {{ block.super }}{% endblock %}

{% block main_content %}
  <p>Estas seguro que quieres eliminar la receta '{{ recipe }}'</p>
  <form method="post" action="">
    {% csrf_token %}
    <input type="submit" value="Eliminar" /> | <a href="{% url 'accounts:recipes' %}">Cancelar</a>
  </form>

{% endblock %}

recipes/templates/recipes/ingredient.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ ingredient.name }} - {{ block.super }}{% endblock %}

{% block css %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/ingredient.css' %}" type="text/css"/>
{% endblock %}

{% block main_content %}
  <h2>{{ingredient.name}}</h2>

<p><strong>Categor&iacute;a:</strong> {{ingredient.category}}</p>
{% if ingredient.image %}
  <p><img src="{{ingredient.image.url}}"></p>
{% endif %}

{% if ingredient_products %}
  <h3>Productos recomendados</h3>
  <ul>
    {% for product in ingredient_products %}
      <li><a href="{% url 'products:product' product.id %}">{{product}}</a></p>
    {% endfor %}
  </ul>
{% endif %}

<div id="nutritional-info">
  <h3>Informaci&oacute;n nutricional:</h3>
  <p><i>Valores por: {{ingredient.serving_size}} gramos.</i></p>
  <p class="first-level">Calor&iacute;as: {{ingredient.calories}}</p>
  <p class="second-level">Calor&iacute;as de grasas: {{ingredient.calories_from_fat}}</p>
  <hr/>
  <p class="first-level">Grasas: {{ingredient.total_fat}}</p>
  <p class="second-level">Saturadas: {{ingredient.saturated_fat}}</p>
  <p class="second-level">Trans: {{ingredient.trans_fat}}</p>
  <p class="second-level">Monoinsaturadas: {{ingredient.mono_fat}}</p>
  <p class="second-level">Poliinsaturados: {{ingredient.polin_fat}}</p>
  <hr/>
  <p class="first-level">Colesterol: {{ingredient.cholesterol}}</p>
  <hr/>
  <p class="first-level">Sales Minerales <i>(Percentuales basados en 2000 calor&iacute;as)</p>
  <p class="second-level">Sodio: {{ingredient.sodium}}</p>
  <p class="second-level">Calcio: {{ingredient.calcium}}</p>
  <p class="second-level">Potasio: {{ingredient.potassium}}</p>
  <p class="second-level">Hierro: {{ingredient.iron}}</p>
  <hr/>
  <p class="first-level">Hidratos de Carbono: {{ingredient.total_carbs}}</p>
  <p class="second-level">Fibra Alimentaria: {{ingredient.dietary_fiber}}</p>
  <p class="second-level">De az&uacute;cares: {{ingredient.sugars}}</p>
  <p class="second-level">De az&uacute;cares a&ntilde;adidos: {{ingredient.added_sugars}}</p>
  <hr/>
  <p class="first-level">Prote&iacute;nas: {{ingredient.protein}}</p>
  <hr/>
  <p class="first-level">Vitaminas: <i>(Percentuales basados en 2000 calor&iacute;as)</p>
  <p class="second-level">Vitamina A: {{ingredient.vitamin_a}}</p>
  <p class="second-level">Vitamina B16: {{ingredient.vitamin_b6}}</p>
  <p class="second-level">Vitamina B12: {{ingredient.vitamin_b12}}</p>
  <p class="second-level">Vitamina C: {{ingredient.vitamin_c}}</p>
  <p class="second-level">Vitamina D: {{ingredient.vitamin_d}}</p>
  <p class="second-level">Vitamina E: {{ingredient.vitamin_e}}</p>
</div>

{% endblock %}

recipes/templates/recipes/meal_form.html
<div>
  <h4>{{ form.meal_type.value }}</h4>
  {{ form.meal_type.as_hidden }}
  <div>
    <label for="{{ form.first_course.id_for_label }}">Primer Plato:</label>{{ form.first_course }}
    <label for="{{ form.first_course_serves.id_for_label }}">Raciones:</label>{{ form.first_course_serves }}
  </div>
  <div>
    <label for="{{ form.second_course.id_for_label }}">Segundo Plato:</label>{{ form.second_course }}
    <label for="{{ form.second_course_serves.id_for_label }}">Raciones:</label>{{ form.second_course_serves }}
  </div>
</div>

recipes/templates/recipes/meal_plan.html
{% extends "base.html" %}

{% block title %}Planificaci&oacute;n - {{ block.super }}{% endblock %}

{% block main_content %}
  <h2>Planificaci&oacute;n</h2>
  <form method="post" action="">
    {% csrf_token %}
    {% include "recipes/meal_day_form.html" with form=today_meals_form %}
    {% include "recipes/meal_day_form.html" with form=tomorrow_meals_form %}
    <input type="submit" value="Aceptar" />
  </form>
{% endblock %}

recipes/templates/recipes/perform_form.html
<p>Para cocinar la receta para  {{ serves }} raciones:</p>
{# <p>Se consumiran los siguientes productos de tu despensa.</p> #}
{# <p>Si no vas a utilizar un producto o vas a utilizar una cantidad diferente, puedes marcar-lo aqu&iacute;.</p> #}

<form method="post" action="">
  {% csrf_token %}

  {% if formset_delete %}
    {{ formset_delete.management_form }}
    {# ugly as hell: we use the post request to see if there was formset_delete #}
    <input type="hidden" name="formset_delete_flag" value="1" />
    {% for form in formset_delete %}
      <div>
	<span>
	  Necesitas: {{ form.recipe_ingredient.value.html_str }} |
	</span>
	<label for="{{ form.quantity.id_for_label }}">Utilizar:</label>{# {{ form.quantity }} #}
	<span>
	  {{ form.product.value.html_str }} | {{ form.use }}
	</span> 
	{{ form.quantity.as_hidden }}
	{{ form.pantry_product_id.as_hidden }}
	{{ form.needed.as_hidden }}
	{{ form.available.as_hidden }}
	{% for field in form %}
	  {{ field.errors }}
	{% endfor %}
      </div>
    {% endfor %}
  {% endif %}

  {% if formset_ask %}
    {# <hr /> #}
    {{ formset_ask.management_form }}
    {# json id matrix... really ugly #}
    <input type="hidden" name="json_id_matrix" value="{{ json_id_matrix }}" />
    {% for form in formset_ask %}
      <div>
	<span>
	  Necesitas: {{ form.recipe_ingredient.value.html_str }} |
	</span>
	<label for="{{ form.quantity.id_for_label }}">Utilizar: </label>
	<span>
	  {{ form.pantry_product }} | {{ form.use }}
	</span>
        {# {{ form.ingredient_quantity.as_hidden }} #}
	{# {{ form.ingredient_unit_id.as_hidden }} #}
	{{ form.recipe_ingredient_id.as_hidden }}
	{% for field in form %}
	  {{ field.errors }}
	{% endfor %}
      </div>
    {% endfor %}
  {% endif %}

  {% if list_missing %}
    <hr />
    <p>Parece que no dispone de ning&uacute;n producto para:</p>
    <ul>
      {% for ingredient_missing in list_missing %}
	<li>
	  {{ ingredient_missing.html_str }}
	</li>
	{% endfor %}  
    </ul>
  {% endif %}

  {% if list_assert %}
    <hr />
    <p>Se asumir&aacute; que usted dispone de:</p>
    <ul>
      {% for ingredient_to_assert in list_assert %}
	<li>
	  {{ ingredient_to_assert.html_str }}
	</li>
      {% endfor %}  
    </ul>
  {% endif %}

  <input type="submit" value="Siguiente" />
</form>

recipes/templates/recipes/perform_recipe.html
{% extends "base.html" %}

{% block title %}Cocinar Receta '{{ recipe }}' - {{ block.super }}{% endblock %}

{% block main_content %}

<h2>Cocinar Receta '{{ recipe }}'</h2>

{% if serves_form %}
  {% include "recipes/serves_form.html" with form=serves_form %}
{% else %}
  {% include "recipes/perform_form.html" %}
{% endif %}

{% endblock %}

recipes/templates/recipes/recipe.html
{% extends "base.html" %}

{% block title %}{{ recipe.name }} - {{ block.super }}{% endblock %}

{% block main_content %}
  <h2>{{recipe.name}}</h2>

<p>Publicada por: <a href="{% url 'accounts:user_profile' recipe.author.id %}">{{recipe.author}}</a> el: {{recipe.pub_date}}</p>

{% if user.is_authenticated %}
  <p><a href="{% url 'recipes:perform_serves' recipe.id %}">Cocinar</a></p>
{% endif %}

{% for final_image in recipe.recipefinalimage_set.all %}
  <p><img src="{{final_image.image.url}}"></p>
{% endfor %}

<p>Listo en: {{recipe.ready_in_time}} minutos</p>
<p>Tiempo de preparaci&oacute;n: {{recipe.preparation_time}} minutos</p>
<p>Tiempo de cocci&oacute;n: {{recipe.cooking_time}} minutos</p>

<p>Raciones: {{recipe.serves}}</p>

<p><b>Categor&iacute;as:</b>
  {% for category in recipe.categories.all %}
    <a href="{% url 'recipes:category' category.id %}">{{category.name}}</a>{% if not forloop.last %}, {% endif %}
  {% endfor %}
</p>

<h3>Ingredientes</h3>
<ul>
  {% for ingredient in recipe.recipeingredient_set.all %}
    <li>{{ingredient.quantity}} {{ingredient.unit}} de <a href="{% url 'recipes:ingredient' ingredient.ingredient.id %}">{{ingredient.ingredient.name}}</a></li>
  {% endfor %}
</ul>

<h3>Instrucciones</h3>

{% for step in recipe.recipestep_set.all %}
  <p>{{forloop.counter}}. {{step.text}}</p>
  {% if step.image %}
    <p><img src="{{step.image.url}}"></p>
  {% endif %}
{% endfor %}

{% endblock %}

recipes/templates/recipes/recipe_category_form.html
<form method="post" action="">
  {% csrf_token %}
  <label for="{{ form.recipe_category.id_for_label }}">Elige Categor&iacute;a:</label>{{ form.recipe_category }}
  <input type="submit" value="Filtrar" />
</form>

recipes/templates/recipes/recipe_form.html
<form method="post" action="">
  {% csrf_token %}
  <div>
    <div><label for="{{ form.name.id_for_label }}">Nombre:</label>{{ form.name }}</div>
    <div>
      <label for="{{ form.preparation_time.id_for_label }}">Tiempo de preparaci&oacute;n:</label>{{ form.preparation_time }}
      <label for="{{ form.cooking_time.id_for_label }}">Tiempo de preparaci&oacute;n:</label>{{ form.cooking_time }}
      <label for="{{ form.ready_in_time.id_for_label }}">Listo en:</label>{{ form.ready_in_time }}
    </div>
    <div><label for="{{ form.serves.id_for_label }}">Raciones:</label>{{ form.serves }}</div>
    <div><label for="{{ form.categories.id_for_label }}">Categor&iacute;as:</label>{{ form.categories }}</div>
  </div>

  <h4>Ingredientes</h4>
  {{ ingredient_formset.management_form }}
  <div>
    {% for ingredient_form in ingredient_formset %}
      {{ ingredient_form.id }}
      <div>
	<label for="{{ ingredient_form.quantity.id_for_label }}">Cantidad:</label>{{ ingredient_form.quantity }}
	<label for="{{ ingredient_form.unit.id_for_label }}">Unidad:</label>{{ ingredient_form.unit }}
	<label for="{{ ingredient_form.ingredient.id_for_label }}">Ingrediente:</label>{{ ingredient_form.ingredient }}
	Eliminar {{ ingredient_form.DELETE }}
      </div>
  {% endfor %}
  </div>

  <h4>Pasos</h4>
  {{ step_formset.management_form }}
  <div>
    {% for step_form in step_formset %}
      {{ step_form.id }}
      <div>
	<div><label for="{{ step_form.text.id_for_label }}">{{ forloop.counter }}.</label>{{ step_form.text }}</div>
	<div><label for="{{ step_form.image.id_for_label }}">Imagen (opcional):</label>{{ step_form.image }}</div>
	Eliminar {{ step_form.DELETE }}
      </div>
      {% endfor %}
  </div>

  <h4>Fotos Finales</h4>
  {{ image_formset.management_form }}
  <div>
    {% for image_form in image_formset %}
      {{ image_form.id }}
      <div>
	<label for="{{ image_form.image.id_for_label }}">Imagen (opcional):</label>{{ image_form.image }}
	Eliminar {{ image_form.DELETE }}
      </div>
    {% endfor %}
  </div>

  
  <input type="submit" value="Finalizar" />
</form>

recipes/templates/recipes/recipes.html
{% extends "base.html" %}

{% block title %}Index de Recetas - {{ block.super }}{% endblock %}

{% block main_content %}
  <h2>Index de Recetas</h2>
  
  {% include "recipes/recipe_category_form.html" %}

  {% include "recipes/recipe_list.html" with recipe_list=recipes %}
{% endblock %}

recipes/templates/recipes/serves_form.html
<form method="post" action="">
  {% csrf_token %}
  <p>Cuantas raciones quieres preparar?</p>
  <div>{{ form.serves }} <input type="submit" value="Siguiente" /></div>
</form>

recipes/templates/recipes/update_meal_plan.html
{% extends "base.html" %}

{% block title %}Planificaci&oacute;n - {{ block.super }}{% endblock %}

{% block main_content %}
  <h2>Planificaci&oacute;n</h2>
  <form method="post" action="">
    {% csrf_token %}
    <h3>{{ today }}</h3>
    {% include "recipes/meal_form.html" with form=today_lunch_form %}
    {% include "recipes/meal_form.html" with form=today_dinner_form %}
    <h3>{{ tomorrow }}</h3>
    {% include "recipes/meal_form.html" with form=tomorrow_lunch_form %}
    {% include "recipes/meal_form.html" with form=tomorrow_dinner_form %}
    <input type="submit" value="Aceptar" />
  </form>
{% endblock %}

recipes/templates/recipes/update_recipe.html
{% extends "base.html" %}

{% block title %}Editando Receta {{ recipe }} - {{ block.super }}{% endblock %}

{% block main_content %}

<h2>Editando Receta {{ recipe }}</h2>

{% include "recipes/recipe_form.html" %}

{% endblock %}