purchases/urls.py
from django.conf.urls import include, url
from purchases import views

urlpatterns = [
    # grocery list
    url(r'^update_grocery_list/$', views.update_grocery_list, name='update_grocery_list'),    
    # pantry
    url(r'^update_pantry/$', views.update_pantry, name='update_pantry'),
    # purchases
    url(r'^create/$', views.create_purchase, name='create_purchase'),
    url(r'^perform/(?P<purchase_id>\d+)/$', views.perform_purchase, name='perform_purchase'),
]

purchases/models.py
from django.db import models

from django.template import defaultfilters

from django.utils import timezone

from accounts.models import UserProfile
from products.models import Product
from stores.models import Store

# MANAGERS

class PurchaseManager(models.Manager):
    def user_pending_purchases(self, user_profile):
        return self.filter(user_profile = user_profile, date__gt=timezone.now(), performed=False)

# MODELS

class GroceryList(models.Model):
    user_profile = models.OneToOneField(UserProfile, unique=True, related_name='grocerylist')

    # methods
    def __str__(self):
        return "Lista de la Compra de " + str(self.user_profile)

class Purchase(models.Model):
    user_profile = models.ForeignKey(UserProfile)
    date = models.DateField()
    performed = models.BooleanField(default=False)

    store = models.ForeignKey(Store)

    # manager
    objects = PurchaseManager()

    # methods
    def __str__(self):
        return "Compra del " + defaultfilters.date(self.date, "l j F")


class Pantry(models.Model):
    user_profile = models.OneToOneField(UserProfile, unique=True)

    # methods
    def last_date_added(self):
        products = PantryProduct.objects.pantry_products(self).order_by('-date_added')
        return products[0].date_added

# products
class BaseProduct(models.Model):
    quantity = models.PositiveIntegerField(default=1)
    product = models.ForeignKey(Product)

    class Meta:
        abstract = True

    def __str__(self):
        return str(self.product)

    # def html_str(self):
    #     return 
            
    # def __str__(self):
    #     return self.quantity + " de " + str(self.product)


class GroceryListProduct(BaseProduct):
    grocery_list = models.ForeignKey(GroceryList)
    date_added = models.DateField(auto_now=True)

class PantryProduct(BaseProduct):
    pantry = models.ForeignKey(Pantry)
    date_added = models.DateField(auto_now=True)        

purchases/templates/purchases/base_product_list.html
<ul>
  {% for product in product_list %}
    <li>{{ product.quantity }} de <a href="{% url 'products:product' product.product.id %}">{{ product.product }}</a></li>
    {# <li>{{ product.html_string }}</li> #}
  {% endfor %}
</ul>

purchases/templates/purchases/create_purchase.html
{% extends "base.html" %}

{% block title %}Nueva Compra - {{ block.super }}{% endblock %}

{% block main_content %}

<h2>Nueva Compra</h2>

<form method="post" action="">
  {% csrf_token %}
  <label for="{{ form.date.id_for_label }}">Fecha:</label>{{ form.date }}{{ form.date.errors }}
  <label for="{{ form.store.id_for_label }}">Tienda:</label>{{ form.store }}{{ form.store.errors }}
  <input type="submit" value="Finalizar" />
</form>

{# {% include "purchases/purchase_form.html" %} #}

{% endblock %}

purchases/templates/purchases/grocery_list.html
{% extends "base.html" %}

{% block title %}Lista de la Compra - {{ block.super }}{% endblock %}

{% block main_content %}

  <h2>Lista de la Compra | <a href="{% url 'purchases:update_grocery_list' %}">Editar</a></h2>

  {% include "purchases/grocery_list_detail.html" %}

{% endblock %}

purchases/templates/purchases/grocery_list_detail.html
{% with grocery_list_products=grocery_list.grocerylistproduct_set.all %}
  {% if grocery_list_products %}
    {% include "purchases/base_product_list.html" with product_list=grocery_list_products %}
  {% else %}
    <p>Tu lista de la compra est&aacute; vac&iacute;a. <a href="{% url 'purchases:update_grocery_list' %}">A&ntilde;adir Productos</a></p>
  {% endif %}
{% endwith %}

purchases/templates/purchases/grocery_list_form.html
<form method="post" action="">
  {% csrf_token %}
  {{ formset.management_form }}
    {% for form in formset %}
      {{ form.id }}
      <div>
	<label for="{{ form.quantity.id_for_label }}">Cantidad:</label>{{ form.quantity }}
	<label for="{{ form.product.id_for_label }}">Producto:</label>{{ form.product }}
	Eliminar {{ form.DELETE }}
      </div>
    {% endfor %}
    <input type="submit" value="Finalizar" />
</form>

purchases/templates/purchases/pantry.html
{% extends "base.html" %}

{% block title %}Despensa - {{ block.super }}{% endblock %}

{% block main_content %}

  <h2>Despensa | <a href="{% url 'purchases:update_pantry' %}">Editar</a></h2>
  
  {% include "purchases/pantry_detail.html" with pantry=user_pantry %}

{% endblock %}

purchases/templates/purchases/pantry_detail.html
{% with pantry_products=pantry.pantryproduct_set.all %}
  {% if pantry_products %}
    {% include "purchases/base_product_list.html" with product_list=pantry_products %}
  {% else %}
    <p>Tu despensa est&aacute; vac&iacute;a.</p>
  {% endif %}
{% endwith %}

purchases/templates/purchases/pantry_form.html
<form method="post" action="">
  {% csrf_token %}
  {{ formset.management_form }}
    {% for form in formset %}
      {{ form.id }}
      <div>
	<label for="{{ form.quantity.id_for_label }}">Cantidad:</label> {{ form.quantity }}
	<label for="{{ form.product.id_for_label }}">Producto:</label>{{ form.product }}
	Eliminar {{ form.DELETE }}
      </div>
    {% endfor %}
    <input type="submit" value="Finalizar" />
</form>

purchases/templates/purchases/pending_purchases.html
{% if pending_purchases %}
  {% for purchase in pending_purchases %}
    <div>
      <h4>{{ purchase }}</h4>
      {% include "purchases/purchase_detail.html" %}
    </div>
  {% endfor %}
{% else %}
<p>No tienes compras pendientes</p>  
{% endif %}

purchases/templates/purchases/perform_purchase.html
{% extends "base.html" %}

{% block main_content %}

  <p>Se efectuar&aacute; la compra con los siguientes productos:</p>

  {% include "purchases/perform_purchase_form.html" %}

{% endblock %}

purchases/templates/purchases/perform_purchase_form.html
<form method="post" action="">
  {% csrf_token %}
  {{ formset.management_form }}
    {% for form in formset %}
      {{ form.id }}
      <div>
	<label for="{{ form.quantity.id_for_label }}">Cantidad:</label> {{ form.quantity }}
	<label for="{{ form.product.id_for_label }}">Producto:</label>{{ form.product }}
	<label for="{{ form.purchased.id_for_label }}">Comprado<label>{{ form.purchased }}
      </div>
    {% endfor %}
    <input type="submit" value="Finalizar" />
</form>

purchases/templates/purchases/purchase_detail.html
<a href="{% url 'purchases:perform_purchase' purchase.id %}">Efectuar</a>

purchases/templates/purchases/update_grocery_list.html
{% extends "base.html" %}

{% block title %}Editando Lista de la Compra - {{ block.super }}{% endblock %}

{% block main_content %}

<h2>Editando Lista de la Compra</h2>

{% include "purchases/grocery_list_form.html" %}

{% endblock %}

purchases/templates/purchases/update_pantry.html
{% extends "base.html" %}

{% block title %}Editando Despensa - {{ block.super }}{% endblock %}

{% block main_content %}

<h2>Editando Despensa</h2>

{% include "purchases/pantry_form.html" %}

{% endblock %}